"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 10:00:01.583306
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('sub_industry', sa.String(length=128), nullable=False),
    sa.Column('in_sp500', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_cik'), ['cik'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_in_sp500'), ['in_sp500'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_ticker'), ['ticker'], unique=True)

    op.create_table('politicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bioguide_id', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('chamber', sa.String(length=8), nullable=False),
    sa.Column('party', sa.String(length=1), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('district', sa.Integer(), nullable=True),
    sa.Column('committees', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('politicians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_politicians_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_politicians_bioguide_id'), ['bioguide_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('telegram_status', sa.String(length=16), nullable=False),
    sa.Column('include_unverified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('company_watches',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'company_id')
    )
    op.create_table('politician_watches',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'politician_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('politician_watches')
    op.drop_table('company_watches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))

    op.drop_table('users')
    with op.batch_alter_table('politicians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_politicians_bioguide_id'))
        batch_op.drop_index(batch_op.f('ix_politicians_active'))

    op.drop_table('politicians')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_ticker'))
        batch_op.drop_index(batch_op.f('ix_companies_in_sp500'))
        batch_op.drop_index(batch_op.f('ix_companies_cik'))

    op.drop_table('companies')
    # ### end Alembic commands ###
