"""trades and alerts

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-28 22:00:18.795319
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingested_days',
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('filings', sa.Integer(), nullable=False),
    sa.Column('trades', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('source', 'day')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('accession_no', sa.String(length=25), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('insider_name', sa.String(length=256), nullable=False),
    sa.Column('insider_title', sa.String(length=256), nullable=False),
    sa.Column('code', sa.String(length=1), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('shares_owned_after', sa.Float(), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('is_10b5_1', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_no', 'code', name='uq_trades_accession_code')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_accession_no'), ['accession_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_filed_date'), ['filed_date'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'trade_id', name='uq_alerts_user_trade')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_trade_id'), ['trade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_trade_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_status'))

    op.drop_table('alerts')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_filed_date'))
        batch_op.drop_index(batch_op.f('ix_trades_company_id'))
        batch_op.drop_index(batch_op.f('ix_trades_accession_no'))

    op.drop_table('trades')
    op.drop_table('ingested_days')
    # ### end Alembic commands ###
